### ISSUE TITLE
Dielectric fix

### ISSUE THREAD

**Issue by Finomnis** [Ufuk-a/raytracer3#1]
This fixes the problem you posted on StackOverflow:

```diff
diff --git a/src/types.rs b/src/types.rs
index 22fd6cd..7f50cec 100644
--- a/src/types.rs
+++ b/src/types.rs
@@ -270,8 +270,8 @@ impl Default for HitRecord {
 impl HitRecord {
     fn set_face_normal(&mut self, r: Ray, outward_normal: Vec3) {

-        let front_face = r.dir.dot(outward_normal) < 0f64;
-        if front_face {
+        self.front_face = r.dir.dot(outward_normal) < 0f64;
+        if self.front_face {
             self.normal = outward_normal;
         } else {
             self.normal = -outward_normal;
```

I found this by stepping through your code with a debugger. I picked the pixel `width/4, height/2` and added an `if` that prints a generic message for that pixel. Then I added a breakpoint to that println and stepped through what actually happens in that pixel. I realized that inside of the `Dielectric` material implementation, the `front_face` was `false`, which doesn't make sense for the first bounce.

I would advise you to practice using the debugger more; problems like this are somewhat easy to find with an interactive debugger.

**Comment by Ufuk-a** [comment]
Thank you!
